spring:
  profiles:
    active: local # default
    group:
      local:
        - common
        - security

---
spring:
  config.activate.on-profile: local
  jpa:
    hibernate:
      ddl-auto: validate
