spring:
  config.activate.on-profile: common
  jpa:
    show-sql: true
    properties.hibernate:
        format_sql: true
    open-in-view: true
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
